[package]
name = "sha2-ex-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../../jolt-sdk" }
inline = { package = "inline-impl", path = "../../inline-impl" }