[package]
name = "big-int-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk" }
ark-ff = { path = "/Users/omid.bodaghi/Desktop/LZ/arkworks-algebra/ff", default-features = false}
ark-bn254 = { path = "/Users/omid.bodaghi/Desktop/LZ/arkworks-algebra/curves/bn254", default-features = false, features = ["curve", "asm"] }
ruint = { version = "1.12", default-features = false }
