[package]
name = "sha2-chain-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = [] }
inlines = { package = "jolt-inlines", path = "../../../jolt-inlines", features = ["sha256"] }
