[package]
name = "sha2-chain-default"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
guest = { package = "sha2-chain-default-guest", path = "./guest" }

hex = "0.4.3"

[features]
icicle = ["jolt-sdk/icicle"]
