[package]
name = "jolt-core"
version = "0.1.0"
authors = [
    # author of original Spartan paper and code base
    "Srinath Setty <srinath@microsoft.com>",
    # authors who contributed to the Arkworks Spartan fork
    "Zhenfei Zhang <zhenfei.zhang@hotmail.com>",
    # authors who contributed to Lasso/Jolt
    "Michael Zhu <mzhu@a16z.com>",
    "Sam Ragsdale <sragsdale@a16z.com>",
    "Noah Citron <ncitron@a16z.com>",
    "Arasu Arun <arasu.arun5@gmail.com>",
    "Quang Dao <dvquang85@gmail.com>",
]
edition = "2021"
description = "The lookup singularity. Based on Spartan; built on Arkworks."
documentation = "https://github.com/a16z/jolt/README.md"
repository = "https://github.com/a16z/jolt"
license-file = "LICENSE"
keywords = ["SNARK", "cryptography", "proofs"]

[features]
default = [
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-std/parallel",
    "ark-ff/asm",
    "host",
    "rayon",
]
host = ["dep:reqwest", "dep:tokio"]
icicle = [
    "default",
    "dep:icicle-runtime",
    "dep:icicle-core",
    "dep:icicle-bn254",
]

[dependencies]
ark-bn254 = { version = "0.5.0", default-features = false, features = ["curve"] }
ark-ec = { version = "0.5.0", default-features = false }
ark-ff = { version = "0.5.0", default-features = false }
ark-serialize = { version = "0.5.0", default-features = false, features = ["derive"] }
ark-serialize-derive = { version = "0.5.0", default-features = false }
ark-std = { version = "0.5.0", default-features = false }
clap = { version = "4.3.10", default-features = false, features = ["default", "derive"] }
enum_dispatch = { version = "0.3.12", default-features = false }
fixedbitset = { version = "0.5.0", default-features = false }
itertools = { version = "0.10.0", default-features = false }
num-integer = { version = "0.1.45", default-features = false }
num-derive = { version = "0.4.2", default-features = false }
num = { version = "0.4.3", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
postcard = { version = "1.0.8", default-features = false, features = ["use-std"] }
rand = { version = "0.7.3", default-features = false, features = ["std"] }
rand_chacha = { version = "0.3.0", default-features = false }
rand_core = { version = "0.6.4", default-features = false }
rayon = { version = "^1.8.0", default-features = false, optional = true }
serde = { version = "1.0.*", default-features = false }
sha3 = { version = "0.10.8", default-features = false, features = ["std"] }
strum = { version = "0.26.3", default-features = false }
strum_macros = { version = "0.26.4", default-features = false }
thiserror = { version = "1.0.58", default-features = false }
tracing = { version = "0.1.37", default-features = false }
tracing-chrome = { version = "0.7.1", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false }
target-lexicon = { version = "0.12.14", default-features = false }
reqwest = { version = "0.12.3", default-features = false, features = ["json", "blocking"], optional = true }
dirs = { version = "5.0.1", default-features = false }
eyre = { version = "0.6.12", default-features = false }
indicatif = { version = "0.17.8", default-features = false }
common = { path = "../common" }
tracer = { path = "../tracer" }
bincode = { version = "1.3.3", default-features = false }
bytemuck = { version = "1.19.0", default-features = false }
tokio = { version = "1.38.0", default-features = false, optional = true }
alloy-primitives = { version = "0.7.6", default-features = false }
alloy-sol-types = { version = "0.7.6", default-features = false }
once_cell = { version = "1.19.0", default-features = false }
rand_distr = { version = "0.4.3", default-features = false }
anyhow = { version = "1.0.97", default-features = false }
derive_more = { version = "2.0.1", default-features = false, features = ["from"] }
paste = { version = "1.0.15", default-features = false }
lazy_static = { version = "1.5.0", default-features = false }

[dev-dependencies]
criterion = { version = "0.5.1", default-features = false, features = ["html_reports"] }
iai-callgrind = { version = "0.10.2", default-features = false }

[build-dependencies]
common = { path = "../common" }

[[bench]]
name = "iai"
harness = false

[[bench]]
name = "grand_product"
harness = false

[[bench]]
name = "commit"
harness = false

[[bench]]
name = "binding"
harness = false

[[bench]]
name = "compute_cubic"
harness = false

[[bench]]
name = "msm"
harness = false

[[bench]]
name = "msm_batch"
harness = false

[[bench]]
name = "msm_adapter_batch"
harness = false

[lib]
name = "jolt_core"
path = "src/lib.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
memory-stats = { version = "1.0.0", default-features = false }
sys-info = { version = "0.9.1", default-features = false }
tokio = { version = "1.38.0", default-features = false, features = ["rt-multi-thread"], optional = true }

[target.'cfg(all(not(target_arch = "wasm32"), target_os = "macos"))'.dependencies]
icicle-core = { git = "https://github.com/ingonyama-zk/icicle-jolt.git", rev = "2441eba", optional = true }
icicle-runtime = { git = "https://github.com/ingonyama-zk/icicle-jolt.git", rev = "2441eba", optional = true }
icicle-bn254 = { git = "https://github.com/ingonyama-zk/icicle-jolt.git", rev = "2441eba", optional = true }

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "macos")))'.dependencies]
icicle-core = { git = "https://github.com/ingonyama-zk/icicle-jolt.git", rev = "2441eba", optional = true }
icicle-runtime = { git = "https://github.com/ingonyama-zk/icicle-jolt.git", rev = "2441eba", features = ["cuda_backend"], optional = true }
icicle-bn254 = { git = "https://github.com/ingonyama-zk/icicle-jolt.git", rev = "2441eba", features = ["cuda_backend"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
