[workspace]
members = [
    "sha2-ex",
    "sha2-ex/guest",
]
resolver = "2"

[profile.release]
debug = 1
lto = "fat"

[workspace.dependencies]
jolt-core = { path = "../../jolt-core", features = ["rv64", "host"] }
jolt-sdk = { path = "../../jolt-sdk" }
jolt-sdk-macros = { path = "../../jolt-sdk/macros" }
common = { path = "../../common" }
tracer = { path = "../../tracer" }
postcard = { version = "1.0.8", default-features = false }
hex-literal = "0.4.1"

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
